# Generated by Django 4.0.1 on 2022-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
