# Generated by Django 4.0.1 on 2022-06-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_topic_comment_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(max_length=3),
        ),
    ]
