# Generated by Django 4.0.1 on 2022-06-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_topic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ManyToManyField(related_name='topics', to='app.Topic'),
        ),
    ]
