# Generated by Django 4.0.1 on 2022-06-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comment_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='subreddit',
            field=models.TextField(default='cryptocurrency', max_length=20),
        ),
    ]
